// AUTH

export const GET_USERNAMES = 'GET_USERNAMES'
export const USERNAMES_FAIL = 'USERNAMES_FAIL'

export const GET_PHONE_NUMS = 'GET_PHONE_NUMS'
export const PHONE_NUMS_FAIL = 'PHONE_NUMS_FAIL'

export const GET_OTP_LOADING = 'GET_OTP_LOADING'
export const GET_OTP_SUCCESS = 'GET_OTP_SUCCESS'
export const GET_OTP_FAIL = 'GET_OTP_FAIL'

export const AUTH_LOADING = 'AUTH_LOADING'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const GET_ME_SUCCESS = 'GET_ME_SUCCESS'
export const GET_ME_FAIL = 'GET_ME_FAIL'
// USER

export const PROFILE_LOADING = 'PROFILE_LOADING'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'
export const EMPTY_PROFILE = 'EMPTY_PROFILE'

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const FOLLOW_LOADING = 'FOLLOW_LOADING'
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS'
export const FOLLOW_FAIL = 'FOLLOW_FAIL'

export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS'
export const UNFOLLOW_FAIL = 'UNFOLLOW_FAIL'

// Communities

export const GET_COMMUNITIES_LOADING = 'GET_COMMUNITIES_LOADING'
export const GET_COMMUNITIES_SUCCESS = 'GET_COMMUNITIES_SUCCESS'
export const GET_COMMUNITIES_FAIL = 'GET_COMMUNITIES_FAIL'

export const GET_COMMUNITY_LOADING = 'GET_COMMUNITY_LOADING'
export const GET_COMMUNITY_SUCCESS = 'GET_COMMUNITY_SUCCESS'
export const GET_COMMUNITY_FAIL = 'GET_COMMUNITY_FAIL'

export const EMPTY_COMMUNITY = 'EMPTY_COMMUNITY'
export const JOIN_LOADING = 'JOIN_LOADING'

export const JOIN_COMMUNITY_SUCCESS = 'JOIN_COMMUNITY_SUCCESS'
export const JOIN_COMMUNITY_FAIL = 'JOIN_COMMUNITY_FAIL'

export const LEAVE_COMMUNITY_SUCCESS = 'LEAVE_COMMUNITY_SUCCESS'
export const LEAVE_COMMUNITY_FAIL = 'LEAVE_COMMUNITY_FAIL'

export const GET_OTHER_POSTS = 'GET_OTHER_POSTS'
export const GET_COMMUNITY_NAMES = 'GET_COMMUNITY_NAMES'
export const COMMUNITY_NAMES_FAIL = 'PHONE_NUMS_FAIL'

// Posts
export const EMPTY_POSTS = 'EMPTY_POSTS'
export const POSTS_LOADING = 'POSTS_LOADING'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'

export const LOADING_COMMENT = 'LOADING_COMMENT'
export const NEW_COMMENT_SUCCESS = 'NEW_COMMENT_SUCCESS'
export const NEW_COMMENT_FAIL = 'NEW_COMMENT_FAIL'

export const LOADING_POST = 'LOADING_POST'
export const EMPTY_SINGLE_POST = 'EMPTY_SINGLE_POST'
export const GET_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS'
export const GET_SINGLE_POST_FAIL = 'GET_SINGLE_POST_FAIL'

export const NEW_POST_SUCCESS = 'NEW_POST_SUCCESS'
export const NEW_POST_FAIL = 'NEW_POST_FAIL'

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const UPVOTE_POST_SUCCESS = 'UPVOTE_POST_SUCCESS'
export const UPVOTE_POST_FAIL = 'UPVOTE_POST_FAIL'

export const DOWNVOTE_POST_SUCCESS = 'DOWNVOTE_POST_SUCCESS'
export const DOWNVOTE_POST_FAIL = 'DOWNVOTE_POST_FAIL'